#edi_pull.R
#code provided by the Environmental Database Initiative for Data Package 2016 with modifications.
#1https://portal.edirepository.org/nis/codeGeneration?packageId=edi.2016.1&statisticalFileType=tidyr
#ingests environmental and phytoplankton data collected in the SLRE 2022-2024


#Package ID: edi.2016.1 Cataloging System:https://pasta.edirepository.org.

#set UserAgent
options(HTTPUserAgent="EDI_CodeGen") 
infile1 <- trimws("https://pasta.lternet.edu/package/data/eml/edi/2016/1/5399ba59c14063eb73fb22633ceb1d82") 
infile1 <-sub("^https","http",infile1)
# This creates a tibble named: edi_definitions 
edi_definitions <-read_delim(infile1  
                 ,delim=","   
                 ,skip=1 
                 ,quote='"'  
                 , col_names=c( 
                   "file",   
                   "header",   
                   "definition",   
                   "method",   
                   "units",   
                   "method.detection.limit"   ), 
                 col_types=list( 
                   col_character(),  
                   col_character(),  
                   col_character(),  
                   col_character(),  
                   col_character(), 
                   col_number() ), 
                 na=c(" ",".","NA","")  )


# Observed issues when reading the data. An empty list is good!
problems(edi_definitions) 

infile2 <- trimws("https://pasta.lternet.edu/package/data/eml/edi/2016/1/67cbac16d66337fd1ea82bb7ba8735ee") 
infile2 <-sub("^https","http",infile2)
# This creates a tibble named: edi_site_info 
edi_site_info <-read_delim(infile2  
                 ,delim=","   
                 ,skip=1 
                 ,quote='"'  
                 , col_names=c( 
                   "site",   
                   "Full.Site.Name",   
                   "Latitude",   
                   "Longitude",   
                   "Notes"   ), 
                 col_types=list( 
                   col_character(),  
                   col_character(), 
                   col_number() , 
                   col_number() ,  
                   col_character()), 
                 na=c(" ",".","NA","")  )


# Observed issues when reading the data. An empty list is good!
problems(edi_site_info) 

infile3 <- trimws("https://pasta.lternet.edu/package/data/eml/edi/2016/1/2453879577c79ec0f9d876049f07bde7") 
infile3 <-sub("^https","http",infile3)
# This creates a tibble named: edi_environ 
edi_environ <-read_delim(infile3  
                 ,delim=","   
                 ,skip=1 
                 ,quote='"'  
                 , col_names=c( 
                   "site",   
                   "sample_type",   
                   "date_sampled",   
                   "time_sampled",   
                   "event",   
                   "depth_m",   
                   "chla",   
                   "tp_ppb",   
                   "op_ppb",   
                   "tn_ppb",   
                   "nh4n_ppb",   
                   "no2no3n_ppb",   
                   "anc_mgLcaco3",   
                   "doc_ppm",   
                   "toc_ppm",   
                   "tss",   
                   "vss",   
                   "odo_percent_sat",   
                   "odo_mg_l",   
                   "sp_cond_m_s_cm",   
                   "turbidity_fnu",   
                   "p_h",   
                   "temp_c",   
                   "PAR_0A",   
                   "PAR_0B",   
                   "PAR_50",   
                   "PAR_100",   
                   "secchi_depth_m",   
                   "pco2_ppm"   ), 
                 col_types=list( 
                   col_character(),  
                   col_character(),  
                   col_date("%m/%d/%Y"),  
                   col_character(), 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() ), 
                 na=c(" ",".","NA","")  )


# Convert Missing Values to NA for individual vectors 
edi_environ$time_sampled <- ifelse((trimws(as.character(edi_environ$time_sampled))==trimws("NA")),NA,edi_environ$time_sampled)               
suppressWarnings(edi_environ$time_sampled <- ifelse(!is.na(as.numeric("NA")) & (trimws(as.character(edi_environ$time_sampled))==as.character(as.numeric("NA"))),NA,edi_environ$time_sampled))
edi_environ$depth_m <- ifelse((trimws(as.character(edi_environ$depth_m))==trimws("NA")),NA,edi_environ$depth_m)               
suppressWarnings(edi_environ$depth_m <- ifelse(!is.na(as.numeric("NA")) & (trimws(as.character(edi_environ$depth_m))==as.character(as.numeric("NA"))),NA,edi_environ$depth_m))
edi_environ$chla <- ifelse((trimws(as.character(edi_environ$chla))==trimws("NA")),NA,edi_environ$chla)               
suppressWarnings(edi_environ$chla <- ifelse(!is.na(as.numeric("NA")) & (trimws(as.character(edi_environ$chla))==as.character(as.numeric("NA"))),NA,edi_environ$chla))
edi_environ$tp_ppb <- ifelse((trimws(as.character(edi_environ$tp_ppb))==trimws("NA")),NA,edi_environ$tp_ppb)               
suppressWarnings(edi_environ$tp_ppb <- ifelse(!is.na(as.numeric("NA")) & (trimws(as.character(edi_environ$tp_ppb))==as.character(as.numeric("NA"))),NA,edi_environ$tp_ppb))
edi_environ$op_ppb <- ifelse((trimws(as.character(edi_environ$op_ppb))==trimws("NA")),NA,edi_environ$op_ppb)               
suppressWarnings(edi_environ$op_ppb <- ifelse(!is.na(as.numeric("NA")) & (trimws(as.character(edi_environ$op_ppb))==as.character(as.numeric("NA"))),NA,edi_environ$op_ppb))
edi_environ$tn_ppb <- ifelse((trimws(as.character(edi_environ$tn_ppb))==trimws("NA")),NA,edi_environ$tn_ppb)               
suppressWarnings(edi_environ$tn_ppb <- ifelse(!is.na(as.numeric("NA")) & (trimws(as.character(edi_environ$tn_ppb))==as.character(as.numeric("NA"))),NA,edi_environ$tn_ppb))
edi_environ$nh4n_ppb <- ifelse((trimws(as.character(edi_environ$nh4n_ppb))==trimws("NA")),NA,edi_environ$nh4n_ppb)               
suppressWarnings(edi_environ$nh4n_ppb <- ifelse(!is.na(as.numeric("NA")) & (trimws(as.character(edi_environ$nh4n_ppb))==as.character(as.numeric("NA"))),NA,edi_environ$nh4n_ppb))
edi_environ$no2no3n_ppb <- ifelse((trimws(as.character(edi_environ$no2no3n_ppb))==trimws("NA")),NA,edi_environ$no2no3n_ppb)               
suppressWarnings(edi_environ$no2no3n_ppb <- ifelse(!is.na(as.numeric("NA")) & (trimws(as.character(edi_environ$no2no3n_ppb))==as.character(as.numeric("NA"))),NA,edi_environ$no2no3n_ppb))
edi_environ$anc_mgLcaco3 <- ifelse((trimws(as.character(edi_environ$anc_mgLcaco3))==trimws("NA")),NA,edi_environ$anc_mgLcaco3)               
suppressWarnings(edi_environ$anc_mgLcaco3 <- ifelse(!is.na(as.numeric("NA")) & (trimws(as.character(edi_environ$anc_mgLcaco3))==as.character(as.numeric("NA"))),NA,edi_environ$anc_mgLcaco3))
edi_environ$doc_ppm <- ifelse((trimws(as.character(edi_environ$doc_ppm))==trimws("NA")),NA,edi_environ$doc_ppm)               
suppressWarnings(edi_environ$doc_ppm <- ifelse(!is.na(as.numeric("NA")) & (trimws(as.character(edi_environ$doc_ppm))==as.character(as.numeric("NA"))),NA,edi_environ$doc_ppm))
edi_environ$toc_ppm <- ifelse((trimws(as.character(edi_environ$toc_ppm))==trimws("NA")),NA,edi_environ$toc_ppm)               
suppressWarnings(edi_environ$toc_ppm <- ifelse(!is.na(as.numeric("NA")) & (trimws(as.character(edi_environ$toc_ppm))==as.character(as.numeric("NA"))),NA,edi_environ$toc_ppm))
edi_environ$vss <- ifelse((trimws(as.character(edi_environ$vss))==trimws("NA")),NA,edi_environ$vss)               
suppressWarnings(edi_environ$vss <- ifelse(!is.na(as.numeric("NA")) & (trimws(as.character(edi_environ$vss))==as.character(as.numeric("NA"))),NA,edi_environ$vss))
edi_environ$odo_percent_sat <- ifelse((trimws(as.character(edi_environ$odo_percent_sat))==trimws("NA")),NA,edi_environ$odo_percent_sat)               
suppressWarnings(edi_environ$odo_percent_sat <- ifelse(!is.na(as.numeric("NA")) & (trimws(as.character(edi_environ$odo_percent_sat))==as.character(as.numeric("NA"))),NA,edi_environ$odo_percent_sat))
edi_environ$odo_mg_l <- ifelse((trimws(as.character(edi_environ$odo_mg_l))==trimws("NA")),NA,edi_environ$odo_mg_l)               
suppressWarnings(edi_environ$odo_mg_l <- ifelse(!is.na(as.numeric("NA")) & (trimws(as.character(edi_environ$odo_mg_l))==as.character(as.numeric("NA"))),NA,edi_environ$odo_mg_l))
edi_environ$sp_cond_m_s_cm <- ifelse((trimws(as.character(edi_environ$sp_cond_m_s_cm))==trimws("NA")),NA,edi_environ$sp_cond_m_s_cm)               
suppressWarnings(edi_environ$sp_cond_m_s_cm <- ifelse(!is.na(as.numeric("NA")) & (trimws(as.character(edi_environ$sp_cond_m_s_cm))==as.character(as.numeric("NA"))),NA,edi_environ$sp_cond_m_s_cm))
edi_environ$turbidity_fnu <- ifelse((trimws(as.character(edi_environ$turbidity_fnu))==trimws("NA")),NA,edi_environ$turbidity_fnu)               
suppressWarnings(edi_environ$turbidity_fnu <- ifelse(!is.na(as.numeric("NA")) & (trimws(as.character(edi_environ$turbidity_fnu))==as.character(as.numeric("NA"))),NA,edi_environ$turbidity_fnu))
edi_environ$p_h <- ifelse((trimws(as.character(edi_environ$p_h))==trimws("NA")),NA,edi_environ$p_h)               
suppressWarnings(edi_environ$p_h <- ifelse(!is.na(as.numeric("NA")) & (trimws(as.character(edi_environ$p_h))==as.character(as.numeric("NA"))),NA,edi_environ$p_h))
edi_environ$temp_c <- ifelse((trimws(as.character(edi_environ$temp_c))==trimws("NA")),NA,edi_environ$temp_c)               
suppressWarnings(edi_environ$temp_c <- ifelse(!is.na(as.numeric("NA")) & (trimws(as.character(edi_environ$temp_c))==as.character(as.numeric("NA"))),NA,edi_environ$temp_c))
edi_environ$PAR_0A <- ifelse((trimws(as.character(edi_environ$PAR_0A))==trimws("NA")),NA,edi_environ$PAR_0A)               
suppressWarnings(edi_environ$PAR_0A <- ifelse(!is.na(as.numeric("NA")) & (trimws(as.character(edi_environ$PAR_0A))==as.character(as.numeric("NA"))),NA,edi_environ$PAR_0A))
edi_environ$PAR_0B <- ifelse((trimws(as.character(edi_environ$PAR_0B))==trimws("NA")),NA,edi_environ$PAR_0B)               
suppressWarnings(edi_environ$PAR_0B <- ifelse(!is.na(as.numeric("NA")) & (trimws(as.character(edi_environ$PAR_0B))==as.character(as.numeric("NA"))),NA,edi_environ$PAR_0B))
edi_environ$PAR_50 <- ifelse((trimws(as.character(edi_environ$PAR_50))==trimws("NA")),NA,edi_environ$PAR_50)               
suppressWarnings(edi_environ$PAR_50 <- ifelse(!is.na(as.numeric("NA")) & (trimws(as.character(edi_environ$PAR_50))==as.character(as.numeric("NA"))),NA,edi_environ$PAR_50))
edi_environ$PAR_100 <- ifelse((trimws(as.character(edi_environ$PAR_100))==trimws("NA")),NA,edi_environ$PAR_100)               
suppressWarnings(edi_environ$PAR_100 <- ifelse(!is.na(as.numeric("NA")) & (trimws(as.character(edi_environ$PAR_100))==as.character(as.numeric("NA"))),NA,edi_environ$PAR_100))
edi_environ$secchi_depth_m <- ifelse((trimws(as.character(edi_environ$secchi_depth_m))==trimws("NA")),NA,edi_environ$secchi_depth_m)               
suppressWarnings(edi_environ$secchi_depth_m <- ifelse(!is.na(as.numeric("NA")) & (trimws(as.character(edi_environ$secchi_depth_m))==as.character(as.numeric("NA"))),NA,edi_environ$secchi_depth_m))
edi_environ$pco2_ppm <- ifelse((trimws(as.character(edi_environ$pco2_ppm))==trimws("NA")),NA,edi_environ$pco2_ppm)               
suppressWarnings(edi_environ$pco2_ppm <- ifelse(!is.na(as.numeric("NA")) & (trimws(as.character(edi_environ$pco2_ppm))==as.character(as.numeric("NA"))),NA,edi_environ$pco2_ppm))


# Observed issues when reading the data. An empty list is good!
problems(edi_environ) 

infile4 <- trimws("https://pasta.lternet.edu/package/data/eml/edi/2016/1/35ec706b24f0a5506f277230a48805da") 
infile4 <-sub("^https","http",infile4)
# This creates a tibble named: edi_do 
edi_do <-read_delim(infile4  
                 ,delim=","   
                 ,skip=1 
                 ,quote='"'  
                 , col_names=c( 
                   "site",   
                   "datetime",   
                   "do_mg_l",   
                   "temp_f",   
                   "do_precent_sat",   
                   "press",   
                   "season"   ), 
                 col_types=list( 
                   col_character(),  
                   col_datetime("%m/%d/%Y %H:%M:%S"), 
                   
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() ,  
                   col_character()), 
                 na=c(" ",".","NA","")  )


# Observed issues when reading the data. An empty list is good!
problems(edi_do) 

infile5 <- trimws("https://pasta.lternet.edu/package/data/eml/edi/2016/1/dfa6fad702f3b083db60b3223079f4c6") 
infile5 <-sub("^https","http",infile5)
# This creates a tibble named: edi_phyto_shape 
edi_phyto_shape <-read_delim(infile5  
                 ,delim=","   
                 ,skip=1 
                 ,quote='"'  
                 , col_names=c( 
                   "SPECIES",   
                   "SPPcode",   
                   "shape_code",   
                   "shape",   
                   "DIV",   
                   "Division",   
                   "L",   
                   "W",   
                   "DP",   
                   "D"   ), 
                 col_types=list( 
                   col_character(),  
                   col_character(),  
                   col_character(),  
                   col_character(),  
                   col_character(),  
                   col_character(), 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() ), 
                 na=c(" ",".","NA","")  )


# Observed issues when reading the data. An empty list is good!
problems(edi_phyto_shape) 

infile6 <- trimws("https://pasta.lternet.edu/package/data/eml/edi/2016/1/d1a47a5cab9e500f91d291ff12cfe4ab") 
infile6 <-sub("^https","http",infile6)
# This creates a tibble named: edi_phyto 
edi_phyto <-read_delim(infile6  
                 ,delim=","   
                 ,skip=1 
                 ,quote='"'  
                 , col_names=c( 
                   "SAMPLE_DATE",   
                   "site",   
                   "event",   
                   "AMASP_BV",   
                   "ANKSP_BV",   
                   "APHFLOS_BV",   
                   "APHSP_BV",   
                   "AULAMBI_BV",   
                   "CENTLAR_BV",   
                   "CENTSMA_BV",   
                   "CENTSMCH_BV",   
                   "CHLSP_BV",   
                   "CNITFRA_BV",   
                   "CROSP_BV",   
                   "CRYREFLEX_BV",   
                   "DOLCCIRL_BV",   
                   "EPXSP_BV",   
                   "GOLRADI_BV",   
                   "GYMSP_BV",   
                   "HAPSP_BV",   
                   "MALSP_BV",   
                   "MCTPUSI_BV",   
                   "MONSP_BV",   
                   "PANLIMNE_BV",   
                   "RHOMINU_BV",   
                   "SYESP_BV",   
                   "UNICOCCH_BV",   
                   "UNICOCCL_BV",   
                   "UNICOCCP_BV",   
                   "UNICOCCY_BV",   
                   "ASTFORM_BV",   
                   "AULGRAN_BV",   
                   "AULSPHEL_BV",   
                   "CRYEROVR_BV",   
                   "FRACROT_BV",   
                   "SYCSP_BV",   
                   "UNICOCCS_BV",   
                   "ZCILSPH_BV",   
                   "ZCODOSP_BV",   
                   "CCCSP_BV",   
                   "CERHIRUN_BV",   
                   "CRYSP_BV",   
                   "DESSP_BV",   
                   "DINDIVER_BV",   
                   "MERSP_BV",   
                   "PSKMILLE_BV",   
                   "RHISP_BV",   
                   "SPCSP_BV",   
                   "TETMINIM_BV",   
                   "ZKERATSP_BV",   
                   "COCSP_BV",   
                   "CRYCMARSS_BV",   
                   "CRYCURVA_BV",   
                   "DINSP_BV",   
                   "EUGSP_BV",   
                   "MELVARI_BV",   
                   "SCHRSP_BV",   
                   "STPCYCSP_BV",   
                   "UNIBAP_BV",   
                   "ZCAULSTE_BV",   
                   "ZCYCCOPE_BV",   
                   "GLESP_BV",   
                   "RHOLENS_BV",   
                   "ZCILFUS_BV",   
                   "ZPOLYASP_BV",   
                   "ZUNICILO_BV",   
                   "ACANTHSP_BV",   
                   "CARSP_BV",   
                   "CRYEROS_BV",   
                   "DINBAVAR_BV",   
                   "OOCPARV_BV",   
                   "ZCGYROM_BV",   
                   "CDINCFCO_BV",   
                   "CRKSP_BV",   
                   "CRUSP_BV",   
                   "EUDSP_BV",   
                   "FRACAPU_BV",   
                   "QUDSP_BV",   
                   "ZTINTISP_BV",   
                   "CHSSP_BV",   
                   "CTHSPRO_BV",   
                   "OCHSP_BV",   
                   "PANMUCIC_BV",   
                   "PEDDUPL_BV",   
                   "AULSP_BV",   
                   "TRESP_BV",   
                   "CHGCELON_BV",   
                   "KEPSP_BV",   
                   "MONMINU_BV",   
                   "TETSP_BV",   
                   "CRHSP_BV",   
                   "COSSP_BV",   
                   "ENTSP_BV",   
                   "SKESP_BV",   
                   "GYRSP_BV",   
                   "PELSP_BV",   
                   "SCESP_BV",   
                   "SYRUVELL_BV",   
                   "AULSPAUX_BV",   
                   "PANMINIM_BV",   
                   "CRLLONGI_BV",   
                   "AULCFISL_BV",   
                   "PLXSP_BV",   
                   "ZCSIGSP_BV",   
                   "NITSP_BV",   
                   "GOMSP_BV",   
                   "KIRSP_BV",   
                   "MICAERUG_BV",   
                   "NAVSP_BV",   
                   "SYRCADAM_BV",   
                   "CRYOVATA_BV",   
                   "CTHSPSQ_BV",   
                   "PERSP_BV",   
                   "CGONIUM_BV",   
                   "PHASP_BV",   
                   "SNOSP_BV",   
                   "UNISTALK_BV",   
                   "DOLCRASS_BV",   
                   "DINCSERT_BV",   
                   "ZPARASP_BV",   
                   "GLOSP_BV",   
                   "MONCONT_BV",   
                   "CUSISSAT_BV",   
                   "EUDELEG_BV",   
                   "ZCOPE_BV",   
                   "COESP_BV",   
                   "CHRURSP_BV",   
                   "PHAELEG_BV",   
                   "RAPCRAC_BV",   
                   "PSKATTE_BV",   
                   "KEPOVALE_BV",   
                   "BITSP_BV",   
                   "DINCYLIN_BV",   
                   "ACHSP_BV",   
                   "DIAVULG_BV",   
                   "EUNSP_BV",   
                   "DIATENU_BV",   
                   "TRASP_BV",   
                   "PANSP_BV",   
                   "COCCCOL_BV",   
                   "SURSP_BV",   
                   "CHMSP_BV",   
                   "NEPSP_BV",   
                   "CHASP_BV",   
                   "DOLPLANC_BV",   
                   "ZBOSSP_BV",   
                   "DIASP_BV",   
                   "MICBOTRY_BV",   
                   "CYDSP_BV",   
                   "TABFLOC_BV",   
                   "CTEPULC_BV",   
                   "PSKCONIC_BV",   
                   "SPMAPHAN_BV",   
                   "DERSP_BV",   
                   "AMAOVAL_BV",   
                   "CRXSP_BV",   
                   "UNITUFT_BV",   
                   "CPLEOD_BV",   
                   "CUSSP_BV",   
                   "EUPSP_BV",   
                   "TRILACUS_BV",   
                   "SCEOBTU_BV",   
                   "ANBSP_BV",   
                   "PEDTETR_BV",   
                   "ZCALCOPE_BV",   
                   "CFCHRCC_BV",   
                   "STAUCYR_BV",   
                   "AMASP_CD",   
                   "ANKSP_CD",   
                   "APHFLOS_CD",   
                   "APHSP_CD",   
                   "AULAMBI_CD",   
                   "CENTLAR_CD",   
                   "CENTSMA_CD",   
                   "CENTSMCH_CD",   
                   "CHLSP_CD",   
                   "CNITFRA_CD",   
                   "CROSP_CD",   
                   "CRYREFLEX_CD",   
                   "DOLCCIRL_CD",   
                   "EPXSP_CD",   
                   "GOLRADI_CD",   
                   "GYMSP_CD",   
                   "HAPSP_CD",   
                   "MALSP_CD",   
                   "MCTPUSI_CD",   
                   "MONSP_CD",   
                   "PANLIMNE_CD",   
                   "RHOMINU_CD",   
                   "SYESP_CD",   
                   "UNICOCCH_CD",   
                   "UNICOCCL_CD",   
                   "UNICOCCP_CD",   
                   "UNICOCCY_CD",   
                   "ASTFORM_CD",   
                   "AULGRAN_CD",   
                   "AULSPHEL_CD",   
                   "CRYEROVR_CD",   
                   "FRACROT_CD",   
                   "SYCSP_CD",   
                   "UNICOCCS_CD",   
                   "ZCILSPH_CD",   
                   "ZCODOSP_CD",   
                   "CCCSP_CD",   
                   "CERHIRUN_CD",   
                   "CRYSP_CD",   
                   "DESSP_CD",   
                   "DINDIVER_CD",   
                   "MERSP_CD",   
                   "PSKMILLE_CD",   
                   "RHISP_CD",   
                   "SPCSP_CD",   
                   "TETMINIM_CD",   
                   "ZKERATSP_CD",   
                   "COCSP_CD",   
                   "CRYCMARSS_CD",   
                   "CRYCURVA_CD",   
                   "DINSP_CD",   
                   "EUGSP_CD",   
                   "MELVARI_CD",   
                   "SCHRSP_CD",   
                   "STPCYCSP_CD",   
                   "UNIBAP_CD",   
                   "ZCAULSTE_CD",   
                   "ZCYCCOPE_CD",   
                   "GLESP_CD",   
                   "RHOLENS_CD",   
                   "ZCILFUS_CD",   
                   "ZPOLYASP_CD",   
                   "ZUNICILO_CD",   
                   "ACANTHSP_CD",   
                   "CARSP_CD",   
                   "CRYEROS_CD",   
                   "DINBAVAR_CD",   
                   "OOCPARV_CD",   
                   "ZCGYROM_CD",   
                   "CDINCFCO_CD",   
                   "CRKSP_CD",   
                   "CRUSP_CD",   
                   "EUDSP_CD",   
                   "FRACAPU_CD",   
                   "QUDSP_CD",   
                   "ZTINTISP_CD",   
                   "CHSSP_CD",   
                   "CTHSPRO_CD",   
                   "OCHSP_CD",   
                   "PANMUCIC_CD",   
                   "PEDDUPL_CD",   
                   "AULSP_CD",   
                   "TRESP_CD",   
                   "CHGCELON_CD",   
                   "KEPSP_CD",   
                   "MONMINU_CD",   
                   "TETSP_CD",   
                   "CRHSP_CD",   
                   "COSSP_CD",   
                   "ENTSP_CD",   
                   "SKESP_CD",   
                   "GYRSP_CD",   
                   "PELSP_CD",   
                   "SCESP_CD",   
                   "SYRUVELL_CD",   
                   "AULSPAUX_CD",   
                   "PANMINIM_CD",   
                   "CRLLONGI_CD",   
                   "AULCFISL_CD",   
                   "PLXSP_CD",   
                   "ZCSIGSP_CD",   
                   "NITSP_CD",   
                   "GOMSP_CD",   
                   "KIRSP_CD",   
                   "MICAERUG_CD",   
                   "NAVSP_CD",   
                   "SYRCADAM_CD",   
                   "CRYOVATA_CD",   
                   "CTHSPSQ_CD",   
                   "PERSP_CD",   
                   "CGONIUM_CD",   
                   "PHASP_CD",   
                   "SNOSP_CD",   
                   "UNISTALK_CD",   
                   "DOLCRASS_CD",   
                   "DINCSERT_CD",   
                   "ZPARASP_CD",   
                   "GLOSP_CD",   
                   "MONCONT_CD",   
                   "CUSISSAT_CD",   
                   "EUDELEG_CD",   
                   "ZCOPE_CD",   
                   "COESP_CD",   
                   "CHRURSP_CD",   
                   "PHAELEG_CD",   
                   "RAPCRAC_CD",   
                   "PSKATTE_CD",   
                   "KEPOVALE_CD",   
                   "BITSP_CD",   
                   "DINCYLIN_CD",   
                   "ACHSP_CD",   
                   "DIAVULG_CD",   
                   "EUNSP_CD",   
                   "DIATENU_CD",   
                   "TRASP_CD",   
                   "PANSP_CD",   
                   "COCCCOL_CD",   
                   "SURSP_CD",   
                   "CHMSP_CD",   
                   "NEPSP_CD",   
                   "CHASP_CD",   
                   "DOLPLANC_CD",   
                   "ZBOSSP_CD",   
                   "DIASP_CD",   
                   "MICBOTRY_CD",   
                   "CYDSP_CD",   
                   "TABFLOC_CD",   
                   "CTEPULC_CD",   
                   "PSKCONIC_CD",   
                   "SPMAPHAN_CD",   
                   "DERSP_CD",   
                   "AMAOVAL_CD",   
                   "CRXSP_CD",   
                   "UNITUFT_CD",   
                   "CPLEOD_CD",   
                   "CUSSP_CD",   
                   "EUPSP_CD",   
                   "TRILACUS_CD",   
                   "SCEOBTU_CD",   
                   "ANBSP_CD",   
                   "PEDTETR_CD",   
                   "ZCALCOPE_CD",   
                   "CFCHRCC_CD",   
                   "STAUCYR_CD"   ), 
                 col_types=list( 
                   col_date("%m/%d/%Y"),   
                   col_character(),  
                   col_character(), 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() ), 
                 na=c(" ",".","NA","")  )


# Observed issues when reading the data. An empty list is good!
problems(edi_phyto) 





